name: Sync Dashboard
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *" # Se actualizeazÄƒ la fiecare 30 min
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Run Script
        run: python tracker.py
      - name: Publish Page
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Update dashboard" || exit 0
          git push
